[project]
name = "minute-physics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black[jupyter]>=24.10.0",
    "plotly>=5.24.1",
    "pandas>=2.2.3",
    "nbformat>=5.10.4",
    "ipykernel>=6.29.5",
]
